#!/usr/bin/env perl

use FindBin;
use Cwd;

my $app_home = $ENV{APP_HOME} || Cwd::realpath("$FindBin::Bin/..");
my $app_host = $ENV{APP_HOST} || "keeper.example.com";
my $app_listen = $ENV{MOJO_LISTEN} || "http://127.0.0.1:5000";

local $/ = undef;
my $config = <DATA>;

$config =~ s!APP_HOME!$app_home!sg;
$config =~ s!APP_HOST!$app_host!sg;
$config =~ s!APP_LISTEN!$app_listen!sg;

print $config;

__DATA__

    server {
        listen 80;
        server_name APP_HOST;
        root  APP_HOME/public;

        location /blob_store {
            internal;
            alias APP_HOME/store/blobs;
        }
        location / {
            try_files $uri @fallback;
        }
        location @fallback {
            proxy_set_header  X-Real-IP        $remote_addr;
            proxy_set_header  X-Forwarded-For  $proxy_add_x_forwarded_for;
            proxy_set_header  Host             $http_host;
            proxy_redirect    off;
            proxy_pass        APP_LISTEN;
            proxy_set_header  X-Real-IP  $remote_addr;
        }
    }

