#!/usr/bin/env perl

use FindBin;
use Cwd;

my $app_home = $ENV{APP_HOME} || Cwd::realpath("$FindBin::Bin/..");
my $app_host = $ENV{APP_HOST} || "keeper.example.com";

local $/ = undef;
my $config = <DATA>;

$config =~ s!APP_HOME!$app_home!sg;
$config =~ s!APP_HOST!$app_host!sg;
$config =~ s!APP_LISTEN!$app_listen!sg;

print $config;

__DATA__

server {
    listen 80;
    server_name APP_HOST;
    root        APP_HOME/public;
    access_log  APP_HOME/log/nginx.access.log;
    error_log   APP_HOME/log/nginx.error.log;

    location /blobs_store {
        internal;
        alias APP_HOME/store/blobs;
    }
    location / {
        try_files $uri @fallback;
    }
    location @fallback {
        include uwsgi_params;
        uwsgi_pass      unix:APP_HOME/log/uwsgi.keeper.sock.1;
        uwsgi_modifier1 5;
    }
}
